name: Build and Deploy to Docker Hub
run-name: Build number ${{ github.run_number }} by ${{ github.actor }}

on:
  push:
    branches: [ "main" ] # Déclenché seulement sur la branche main
  workflow_dispatch: # Permet de le lancer manuellement

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Étape 1: Récupère le code de votre dépôt
      - name: Checkout Code
        run: |
           echo ${{secrets.GITHUB_TOKEN}}
          echo ${{secrets.DOCKERHUB_USERNAME}}
          echo ${{secrets.DOCKERHUB_TOKEN}}
        uses: actions/checkout@v4

      # Étape 2: Connexion à Docker Hub
      # Utilise les secrets pour une connexion sécurisée
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Étape 3: Construit l'image et la pousse sur Docker Hub
      # Remplacez "ga" par le nom de votre dépôt sur Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sp:latest