name: Build and Deploy to Azure Container Registry
run-name: Build number ${{ github.run_number }} by ${{ github.actor }}

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: |
            az acr login --name ${{ secrets.ACR_NAME }}
          

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
            context: .
            push: true
            tags: ${{ secrets.ACR_NAME }}.azurecr.io/kida-store-app:latest

      - name: Restart Azure App Service 🔄
        uses: azure/cli@v1
        with:
          inlineScript: |
            az webapp restart --name ${{ secrets.AZURE_WEBAPP_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }}

